[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
# Set GOOGLE_MAPS_API_KEY in Netlify dashboard under Site settings > Environment variables